### ISSUE TITLE
[Bug] Windows user containing non-ANSI characters (e.g. ä) causes Unity Editor crash in Firestore

### ISSUE THREAD

**Issue by Karottenrambo** [firebase/firebase-unity-sdk#351]
* Unity editor version: 2021.3.1f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Analytics
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android, and desktop editor
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Accessing the Firestore DB constantly crashes/closes the Unity editor without a freeze or a crashlog.
It does not matter if I get a DocumentReference, or try to read or write data.
Running the same code on an actual android device works.

#### Steps to reproduce:

Followed the basic Add Firebase to your Unity Game Firecast:

https://www.youtube.com/watch?v=b5h1bVGhuRk&t=283s

I already tried creating an separate Firestore Instance like so:
FirebaseFirestore db = FirebaseFirestore.GetInstance(Firebase.FirebaseApp.Create());

working with the default instance does not work either.

The issue looks similar to this, but I already tried the suggested solutions and it should be fixed in the new SDK version anyways:
https://github.com/firebase/quickstart-unity/issues/638

Unity created the "google-services-desktop" config file, but it's identical to the original "google-services" file, should that be the case?

**Comment by deveshbeniwal** [comment]
The same thing happening with me too!
![image](https://user-images.githubusercontent.com/37548150/175760940-ef32f6e4-35a3-4c01-800c-e695bf907269.png)
This is my crash log
.
.
Unity - 2021.3.5
Firebase Firestone sdk - 9.1.0
.
I tried in new project and still have issue! Tried downgrading the sdk version but still not working.

Wherever the write "CollectionReference usersRef = db.Collection("users");" Editor get crashed. Please give solution asap. i have to deliver the project

**Comment by deveshbeniwal** [comment]
I don;t even have ANSI Characters but still crashing the same way as @Karottenrambo

**Comment by dconeybe** [comment]
@deveshbeniwal Could you open a new issue and paste your stack trace? Perhaps there is something subtly different in your case and we can take a look.

**Comment by dconeybe** [comment]
For the record, I closed it as a duplicate.

Here is the canonical issue for your problem: https://github.com/firebase/quickstart-unity/issues/1284

**Comment by deveshbeniwal** [comment]
@dconeybe then what should i do now? Should i make a new bug or you'll reopen this? Or working on this one only?

**Comment by dconeybe** [comment]
@deveshbeniwal You should just follow https://github.com/firebase/quickstart-unity/issues/1284. If you have follow up questions or want to otherwise continue discussion please do so on that issue. But for now, there is no fix or known workaround.

**Comment by deveshbeniwal** [comment]
@dconeybe Got the solution! Unity project is making multiple instances for firestore or realtime database so we have to make it persistant after taking instance. You can declare instance like below - 

        db = FirebaseFirestore.DefaultInstance;
        db.Settings.PersistenceEnabled = false;

NOTE : PersistenceEnabled must be false.
Also this error might thorugh from firebase while we initialize instance. HOPE this will be get solved in next updates

**Comment by avodhel** [comment]
> That video was actually incredibly helpful! I noticed something subtle. I believe you are experiencing [firebase/firebase-cpp-sdk#728](https://github.com/firebase/firebase-cpp-sdk/issues/728). Basically, if the path to your %USERPROFILE% folder contains non-ANSI characters (e.g. ä) then this causes a crash on Windows. If you're able, could you try creating a user with only plain ANSI characters and try the same steps when logging in as that user?

Is there any progress about this issue?

**Comment by dconeybe** [comment]
@avodhel Apologies, but no, there has been no progress on a fix for this issue.

**Comment by AlejandroGUnity** [comment]
@dconeybe Hi!
Is there any update on this bug? My team and I are working for Asian companies and clients whom are very likely to have non-ANSI character in their computers and can't create new users. 

Is there any ETA? 
We are currently using the Firebase SDK 9.4.0 in Unity 2022.1.14f1 and still experiencing this issue.

If not, is there any way we could try and solve this ourselves?

**Comment by dconeybe** [comment]
Unfortunately, no, there is no update on this bug and no ETA. The Firestore team, unfortunately, is not able to prioritize working on this bug at this time.

Back when I was investigating this issue, the place where I got stuck was figuring out how to get leveldb (https://github.com/google/leveldb) to open a database at a path that contains non-ANSI characters on Windows. I just couldn't figure out how to do it, and that is why Unity is crashing when there are non-ANSI characters in the path. Apparently Chromium (https://github.com/chromium/chromium) has no issue with this so I was trying to figure out how that project worked around this issue. But I was never able to find a solution, and my priorities have since shifted.

If anyone is ambitious and can figure out how to get leveldb to open a database on Windows at a path containing non-ANSI characters that would be incredibly helpful. I know I could figure it out given enough time, but I just don't have the time right now.

**Comment by yubingxdc** [comment]
any update for this issue?

**Comment by dconeybe** [comment]
This issue is fixed in v11.1.0 (https://firebase.google.com/support/release-notes/unity#version_1110_-_june_01_2023). Please try it out!
